homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  # Packages
  packages: !include_dir_named packages

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Lovelace
lovelace:
  mode: yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# MySQL instead of SQLite
recorder:
  db_url: !secret database
  purge_keep_days: 3
  # include:
  #   domains:
  #     - device_tracker
  #     - light
  #   entities:
  #     - climate.woonkamer
  #     - sensor.temperature_158d00027308f7
  #     - sensor.temperature_158d000272fed0
  #     - sensor.cv_druk
  #     - sensor.wasmachine_watts
  #     - sensor.droger_watts
  #     - binary_sensor.door_window_sensor_158d00022daba6
  #     - binary_sensor.door_window_sensor_158d0002518b9d
  #     - binary_sensor.door_window_sensor_158d00027502b6
  #     - binary_sensor.door_window_sensor_158d0002bf9d5c
  #     - binary_sensor.door_window_sensor_158d0002434bb7
  #     - binary_sensor.motion_sensor_158d0002b48e7e
  #     - binary_sensor.motion_sensor_158d0002b5d5d1
  #     - binary_sensor.motion_sensor_158d0002b4331f
  #     - binary_sensor.water_leak_sensor_158d00023a4bcf
  #     - sensor.power_consumption

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: 'nl'

# Cloud
cloud:

# System health
system_health:

# Xiaomi
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_gateway_key

# Asus router
asuswrt:
  host: !secret asuswrt_host
  username: !secret asuswrt_username
  password: !secret asuswrt_password
device_tracker:
  - platform: asuswrt
    track_new_devices: False
  - platform: google_maps
    username: !secret google_username
    password: !secret google_password
    max_gps_accuracy: 100

# Zones
zone:
  - name: justbetter
    latitude: !secret justbetter_latitude
    longitude: !secret justbetter_longitude
    icon: mdi:office-building
  - name: kapsalon
    latitude: !secret kapsalon_latitude
    longitude: !secret kapsalon_longitude
    icon: mdi:content-cut

# ZoneMinder
zoneminder:
  host: !secret zoneminder_host
  username: !secret zoneminder_username
  password: !secret zoneminder_password
camera:
  - platform: zoneminder

climate:
  # InComfort
  - platform: InComfort
    name: Woonkamer
    host: !secret incomfort_host

sensor:
  # Plex server
  - platform: plex
    name: Plex server
    host: !secret plex_host_remote
    username: !secret plex_username
    password: !secret plex_password
  # Plex home
  - platform: plex
    name: Plex home
    host: !secret plex_host_home
    username: !secret plex_username
    password: !secret plex_password
  # Weer
  - platform: buienradar
    monitored_conditions:
      - condition
      - conditiondetailed
      - symbol
      - temperature
  # PostNL
  - platform: postnl
    name: PostNL
    username: !secret postnl_username
    password: !secret postnl_password
  # Xiaomi Flower Care (also see the "plant" configuration)
  - platform: miflora
    name: plant 1
    mac: 'C4:7C:8D:67:3F:51'
  - platform: miflora
    name: plant 2
    mac: 'C4:7C:8D:67:3E:BB'
  - platform: miflora
    name: plant 3
    mac: 'C4:7C:8D:67:3E:12'
  - platform: miflora
    name: plant 4
    mac: 'C4:7C:8D:6A:9E:DB'
  - platform: miflora
    name: plant 5
    mac: 'C4:7C:8D:6A:9F:98'
  # Droger
  - platform: template
    sensors:
      droger_amps:
        friendly_name_template: "{{ states.switch.droger.name}} amperage"
        value_template: '{{ states.switch.droger.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      droger_watts:
        friendly_name_template: "{{ states.switch.droger.name}} wattage"
        value_template: '{{ states.switch.droger.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      droger_total_kwh:
        friendly_name_template: "{{ states.switch.droger.name}} totaal"
        value_template: '{{ states.switch.droger.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      droger_volts:
        friendly_name_template: "{{ states.switch.droger.name}} voltage"
        value_template: '{{ states.switch.droger.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      droger_today_kwh:
        friendly_name_template: "{{ states.switch.droger.name}} vandaag"
        value_template: '{{ states.switch.droger.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
  # Wasmachine
  - platform: template
    sensors:
      wasmachine_amps:
        friendly_name_template: "{{ states.switch.wasmachine.name}} amperage"
        value_template: '{{ states.switch.wasmachine.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      wasmachine_watts:
        friendly_name_template: "{{ states.switch.wasmachine.name}} wattage"
        value_template: '{{ states.switch.wasmachine.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      wasmachine_total_kwh:
        friendly_name_template: "{{ states.switch.wasmachine.name}} totaal"
        value_template: '{{ states.switch.wasmachine.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      wasmachine_volts:
        friendly_name_template: "{{ states.switch.wasmachine.name}} voltage"
        value_template: '{{ states.switch.wasmachine.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      wasmachine_today_kwh:
        friendly_name_template: "{{ states.switch.wasmachine.name}} vandaag"
        value_template: '{{ states.switch.wasmachine.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
  # Jacuzzi
  - platform: template
    sensors:
      jacuzzi_amps:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} amperage"
        value_template: '{{ states.switch.jacuzzi.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      jacuzzi_watts:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} wattage"
        value_template: '{{ states.switch.jacuzzi.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      jacuzzi_total_kwh:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} totaal"
        value_template: '{{ states.switch.jacuzzi.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      jacuzzi_volts:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} voltage"
        value_template: '{{ states.switch.jacuzzi.attributes["voltage"] | float }}'
        unit_of_measurement: 'V'
      jacuzzi_today_kwh:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} vandaag"
        value_template: '{{ states.switch.jacuzzi.attributes["today_energy_kwh"] | float }}'
        unit_of_measurement: 'kWh'
      jacuzzi_today_kwh_euro:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} vandaag"
        value_template: '{{ (states.switch.jacuzzi.attributes["today_energy_kwh"] | float * 0.22) | round(2) }}'
        unit_of_measurement: 'euro'
      jacuzzi_total_kwh_euro:
        friendly_name_template: "{{ states.switch.jacuzzi.name}} totaal"
        value_template: '{{ (states("sensor.jacuzzi_yearly") | float * 0.22) | round(2) }}'
        unit_of_measurement: 'euro'
  # DSMR
  - platform: dsmr
    port: /dev/ttyUSB0
    dsmr_version: 5
  # Power Consumption merged
  - platform: template
    sensors:
      power_consumption_all:
        friendly_name: "Power Consumption (all)"
        value_template: "{{ (states('sensor.power_consumption_normal') | float + states('sensor.power_consumption_low') | float) | round(3) }}"
        unit_of_measurement: 'kWh'
  # CV Pressure
  - platform: rest
    resource: !secret incomfort_data_url
    name: CV Druk
    device_class: pressure
    unit_of_measurement: Bar
    value_template: '{{ (value_json.ch_pressure_lsb + value_json.ch_pressure_msb * 256) / 100 }}'

utility_meter:
  gas_monthly:
    source: sensor.gas_consumption
    cycle: monthly
  gas_yearly:
    source: sensor.gas_consumption
    cycle: yearly
  energy_monthly:
    source: sensor.power_consumption_all
    cycle: monthly
  energy_yearly:
    source: sensor.power_consumption_all
    cycle: yearly
  jacuzzi_daily:
    source: sensor.jacuzzi_total_kwh
    cycle: daily
  jacuzzi_weekly:
    source: sensor.jacuzzi_total_kwh
    cycle: weekly
  jacuzzi_monthly:
    source: sensor.jacuzzi_total_kwh
    cycle: monthly
  jacuzzi_yearly:
    source: sensor.jacuzzi_total_kwh
    cycle: yearly

# Xiaomi Flower Care (also see the "sensor" configuration)
plant:
  plant_1:
    sensors:
      moisture: sensor.plant_1_moisture
      battery: sensor.plant_1_battery
      temperature: sensor.plant_1_temperature
      conductivity: sensor.plant_1_conductivity
      brightness: sensor.plant_1_light_intensity
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 1000
    min_temperature: 12
    max_temperature: 32
    min_brightness: 800
    max_brightness: 20000
  plant_2:
    sensors:
      moisture: sensor.plant_2_moisture
      battery: sensor.plant_2_battery
      temperature: sensor.plant_2_temperature
      conductivity: sensor.plant_2_conductivity
      brightness: sensor.plant_2_light_intensity
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 15
    max_temperature: 32
    min_brightness: 1500
    max_brightness: 35000
  plant_3:
    sensors:
      moisture: sensor.plant_3_moisture
      battery: sensor.plant_3_battery
      temperature: sensor.plant_3_temperature
      conductivity: sensor.plant_3_conductivity
      brightness: sensor.plant_3_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 32
    min_brightness: 2000
    max_brightness: 35000
  plant_4:
    sensors:
      moisture: sensor.plant_4_moisture
      battery: sensor.plant_4_battery
      temperature: sensor.plant_4_temperature
      conductivity: sensor.plant_4_conductivity
      brightness: sensor.plant_4_light_intensity
    min_moisture: 15
    max_moisture: 65
    min_conductivity: 350
    max_conductivity: 1000
    min_temperature: 12
    max_temperature: 32
    min_brightness: 800
    max_brightness: 20000
  plant_5:
    sensors:
      moisture: sensor.plant_5_moisture
      battery: sensor.plant_5_battery
      temperature: sensor.plant_5_temperature
      conductivity: sensor.plant_5_conductivity
      brightness: sensor.plant_5_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 5
    max_temperature: 35
    min_brightness: 2000
    max_brightness: 55000

# Light groups
light:
  - platform: group
    name: Alles
    entities:
      - light.bank
      - light.gateway_light_7811dcded48c
      - light.verlichting_hal
      - light.verlichting_eettafel
      - light.overloop
      - light.slaapkamer
      - light.logeerkamer
      - light.verlichting_zolder
      - light.verlichting_batcave
  - platform: group
    name: Verlichting hal
    entities:
      - light.deur
      - light.kapstok
      - light.trap
  - platform: group
    name: Verlichting eettafel
    entities:
      - light.eettafel_1
      - light.eettafel_2
  - platform: group
    name: Verlichting Batcave
    entities:
      - light.bureau
      - light.kastjes
      - light.muur
  - platform: group
    name: Verlichting zolder
    entities:
      - light.droger
      - light.hoek
      - light.kastje

# Xiaomi Vacuum
vacuum:
  - platform: xiaomi_miio
    name: Berta
    host: !secret berta_host
    token: !secret berta_token

# Pushover Notifications
notify:
   - platform: pushover
     api_key: !secret pushover_api_key
     user_key: !secret pushover_user_key

# Buienradar
weather:
  - platform: buienradar

# Alarm
alarm_control_panel:
  - platform: manual
    name: Alarm

# TP-Link
tplink:
  switch:
    # Droger
    - host: 192.168.1.7
    # Wasmachine
    - host: 192.168.1.8
    # Jacuzzi
    - host: 192.168.1.9

# Google Assistant
google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
    - media_player
    - climate
    - vacuum
  entity_config:
    light.alles:
      name: "Alle verlichting"
    light.verlichting_batcave:
      room: Mancave
    light.verlichting_hal:
      room: Hal
    light.verlichting_eettafel:
      room: Woonkamer
    light.verlichting_zolder:
      room: Zolder
    vacuum.berta:
      room: Woonkamer
    light.gateway_light_7811dcded48c:
      room: Keuken

# Iframes
panel_iframe:
  zoneminder:
    title: ZoneMinder
    url: !secret iframe_zoneminder
    icon: mdi:cctv
  plex:
    title: Plex
    url: !secret iframe_plex
    icon: mdi:plex

automation: !include automations.yaml
script: !include scripts.yaml
