title: De Hofstee 18
views:
  - path: home
    icon: mdi:home-assistant
    cards:
      - type: picture-entity
        entity: camera.voor
        show_name: false
        show_state: false
      - type: picture-entity
        entity: camera.tuin
        show_name: false
        show_state: false
  - path: verlichting
    icon: mdi:lightbulb
    title: Verlichting
    cards:
      - type: entities
        entities:
          - entity: light.alles
            name: Alles
            icon: mdi:brightness-4
          - type: divider
          - entity: light.bank
            icon: mdi:sofa
          # - entity: switch.kerstboom
          #   name: Kerstboom
          #   icon: mdi:pine-tree
          - entity: light.verlichting_eettafel
            name: Eettafel
            icon: mdi:silverware-fork-knife
          - entity: light.verlichting_hal
            name: Hal
            icon: mdi:door
          - type: divider
          - entity: light.overloop
            name: Overloop
            icon: mdi:stairs
          - entity: light.slaapkamer
            name: Slaapkamer
            icon: mdi:bed-empty
          - entity: light.kledingkast
            name: Kledingkast
            icon: mdi:tshirt-crew
          - entity: light.logeerkamer
            name: Logeerkamer
            icon: mdi:hotel
          - type: divider
          - entity: light.verlichting_zolder
            name: Zolder
            icon: mdi:washing-machine
          - entity: light.verlichting_batcave
            name: Batcave
            icon: mdi:bat
          - type: divider
          - entity: switch.voortuin
            name: Voortuin
            icon: mdi:flower-tulip
          - entity: switch.tuin_verlichting_2
            name: Achtertuin
            icon: mdi:flower
          - entity: switch.tuin_verlichting
            name: Stopcontacten
            icon: mdi:power-socket-eu
      - type: vertical-stack
        cards:
          - type: entities
            title: Woonkamer
            entities:
              - light.bank
              - light.gateway_light_7811dcded48c
          - type: entities
            title: Eettafel
            show_header_toggle: false
            entities:
              - entity: light.verlichting_eettafel
                name: Alle 2
              - light.eettafel_1
              - light.eettafel_2
          - type: entities
            title: Hal
            show_header_toggle: false
            entities:
              - entity: light.verlichting_hal
                name: Alle 3
              - light.deur
              - light.kapstok
              - light.trap
      - type: vertical-stack
        cards:
          - type: entities
            title: Boven
            show_header_toggle: false
            entities:
              - light.overloop
              - light.slaapkamer
              - light.logeerkamer
              - light.kledingkast
      - type: vertical-stack
        cards:
          - type: entities
            title: Zolder
            show_header_toggle: false
            entities:
              - entity: light.verlichting_zolder
                name: Alle 3
              - light.droger
              - light.hoek
              - light.kastje
          - type: entities
            title: Batcave
            show_header_toggle: false
            entities:
              - entity: light.verlichting_batcave
                name: Alle 3
              - light.bureau
              - light.kastjes
              - light.muur
  - path: klimaat
    icon: mdi:thermometer
    title: Klimaat
    cards:
      - type: thermostat
        entity: climate.woonkamer
      - type: entities
        entities:
          - sensor.temperature_slaapkamer
          - sensor.temperature_mancave
          - sensor.cv_druk
      - type: entities
        entities:
          - sensor.humidity_slaapkamer
          - sensor.humidity_mancave
  - path: schoonmaak
    icon: mdi:broom
    title: Schoonmaak
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          entities:
            - vacuum.berta
            - entity: script.1546891798335
              icon: mdi:delete-restore
            - entity: script.1549895117036
              icon: mdi:sofa
            - entity: script.1549991292833
              icon: mdi:food-fork-drink
            - type: divider
            - entity: switch.wasmachine
              icon: mdi:washing-machine
            - entity: switch.droger
              icon: mdi:tumble-dryer
        - type: horizontal-stack
          cards:
            - type: gauge
              entity: sensor.wasmachine_watts
              title: Wasmachine
              max: 3680
              severity:
                green: 0
                yellow: 1000
                red: 3000
            - type: gauge
              entity: sensor.droger_watts
              title: Droger
              max: 3680
              severity:
                green: 0
                yellow: 1000
                red: 3000
  - path: alarm
    icon: mdi:bell
    title: Alarm
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.alarm
      - type: vertical-stack
        cards:
        - type: entities
          entities:
            - entity: binary_sensor.door_window_sensor_voordeur
              icon: mdi:door
            - entity: binary_sensor.door_window_sensor_achterdeur
              icon: mdi:door
            - entity: binary_sensor.door_window_sensor_badkamer
              icon: mdi:window-closed
            - entity: binary_sensor.door_window_sensor_logeerkamer
              icon: mdi:window-closed
            - entity: binary_sensor.door_window_sensor_slaapkamer
              icon: mdi:window-closed
            - entity: binary_sensor.door_window_sensor_zolder
              icon: mdi:window-closed
        - type: entities
          entities:
            - binary_sensor.motion_sensor_hal
            - binary_sensor.motion_sensor_trap
            - binary_sensor.motion_sensor_keuken
        - type: entities
          entities:
            - binary_sensor.water_leak_sensor_wasmachine
  - path: jacuzzi
    icon: mdi:pool
    title: Jacuzzi
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          entities:
            - entity: switch.jacuzzi
              icon: mdi:power
              name: Aan/uit
            - entity: sensor.temperature_jacuzzi
              name: Temperatuur
            - type: divider
            - entity: sensor.jacuzzi_today_kwh
              icon: mdi:flash
              name: Verbruik vandaag
            - entity: sensor.jacuzzi_today_kwh_euro
              icon: mdi:currency-eur
              name: Kosten vandaag
            - type: divider
            - entity: sensor.jacuzzi_total_kwh
              icon: mdi:flash
              name: Verbruik totaal
            - entity: sensor.jacuzzi_total_kwh_euro
              icon: mdi:currency-eur
              name: Kosten totaal
        - type: gauge
          entity: sensor.jacuzzi_watts
          title: Jacuzzi
          max: 3680
          severity:
            green: 0
            yellow: 1000
            red: 3000

  - path: planten
    icon: mdi:flower
    title: Planten
    cards:
      - type: vertical-stack
        cards:
          - type: plant-status
            entity: plant.plant_3
            name: Voortafel (Begonia Maculata Raddi)
          - type: plant-status
            entity: plant.plant_1
            name: Hoek (Calathea Insignis)
          - type: plant-status
            entity: plant.plant_4
            name: Eettafel (Calathea Stromata)
          - type: plant-status
            entity: plant.plant_2
            name: Achterraam (Anthurium Andraeanum)
          - type: plant-status
            entity: plant.plant_5
            name: Achterraam (Senecio Serpens)
  - path: lokatie
    icon: mdi:map-marker
    title: Lokatie
    cards:
      - type: glance
        entities:
        - device_tracker.google_maps_109661945099680068664
        - device_tracker.google_maps_117696366411650505303
      - type: map
        entities:
        - device_tracker.google_maps_109661945099680068664
        - device_tracker.google_maps_117696366411650505303
        default_zoom: 12
  - path: multimedia
    icon: mdi:youtube-tv
    title: Multimedia
    badges:
      - sensor.plex_home
      - sensor.plex_server
    cards:
      - type: media-control
        entity: media_player.chromecast_rm
      - type: media-control
        entity: media_player.googlehome5965
      - type: media-control
        entity: media_player.batcave
  - path: meterstanden
    icon: mdi:flash
    title: Meterstanden
    cards:
      - type: entities
        entities:
          - sensor.power_consumption
          - sensor.gas_consumption
          - entity: sensor.power_consumption_all
            icon: mdi:flash
          - sensor.long_power_failure_count
      - type: history-graph
        entities:
          - sensor.power_consumption
  - path: batterijen
    icon: mdi:battery
    title: Batterijen
    cards:
      - type: entities
        entities:
          - entity: sensor.tradfri_remote_control
            name: Afstandsbediening bank
            icon: mdi:remote
          - entity: sensor.schakelaar_tuin
            name: Afstandsbediening tuin
            icon: mdi:remote
  - path: weer
    icon: mdi:weather-cloudy
    title: weer
    badges:
      - sun.sun
      - sensor.br_symbol
    cards:
      - type: weather-forecast
        entity: weather.br_unknown_station
  - path: floorplan
    icon: mdi:floor-plan
    title: Floorplan
    cards:
      - type: picture-elements
        image: https://cloud.funda.nl/valentina_media/087/240/930_2160.jpg
        elements:
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.bank
            style:
              top: 79%
              left: 16%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.verlichting_hal
            style:
              top: 71%
              left: 46%
          - type: state-label
            entity: climate.woonkamer
            style:
              top: 76%
              left: 40%

# state-badge
# state-label
# service-button
# icon
# image
