automation:
  - alias: Licht eettafel andere kleur cube flip 90
    trigger:
    - event_data:
        action_type: flip90
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    action:
    - service: light.turn_on
      entity_id: light.verlichting_eettafel
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}']

  - alias: Licht eettafel blauw cube flip 180
    trigger:
    - event_data:
        action_type: flip180
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    action:
    - service: light.turn_on
      entity_id: light.verlichting_eettafel
      data_template:
        rgb_color: [0,0,255]

  - alias: Licht eettafel normaal cube tap twice
    trigger:
    - event_data:
        action_type: tap_twice
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    action:
    - service: light.turn_on
      entity_id: light.verlichting_eettafel
      data_template:
        rgb_color: [255,171,88]

  - alias: Licht eettafel vel cube move
    trigger:
    - event_data:
        action_type: move
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    action:
    - service: light.turn_on
      entity_id: light.verlichting_eettafel
      data_template:
        brightness: 255

  - alias: Licht eettafel dimmen cube rotate
    trigger:
    - event_data:
        action_type: rotate
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    action:
    - service: light.turn_on
      entity_id: light.verlichting_eettafel
      data_template:
        brightness: >
          {% if states.light.verlichting_eettafel.attributes.brightness + (trigger.event.data.action_value | round()) > 254 %}
            254
          {% elif states.light.verlichting_eettafel.attributes.brightness + (trigger.event.data.action_value | round()) < 1 %}
            1
          {% else %}
            {{ states.light.verlichting_eettafel.attributes.brightness + (trigger.event.data.action_value | round()) }}
          {% endif %}

  - alias: Licht eettafel uit cube shake
    trigger:
    - event_data:
        action_type: shake_air
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    condition:
    - condition: state
      entity_id: light.verlichting_eettafel
      state: 'on'
    action:
    - service: light.turn_off
      entity_id: light.verlichting_eettafel

  - alias: Alle verlichting uit cube free fall
    trigger:
    - event_data:
        action_type: free_fall
        entity_id: binary_sensor.cube_158d00028f75a0_2
      event_type: xiaomi_aqara.cube_action
      platform: event
    condition:
    - condition: state
      entity_id: light.alles
      state: 'on'
    action:
    - service: light.turn_off
      entity_id: light.alles
